apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"