apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db
spec:
  storageClassName: manual # do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi